openapi: 3.0.1
info:
  title: API Documentation
  description: OpenAPI documentation
  version: 1.0.0
servers:
  - url: "http://localhost:8080/bff"
    description: Generated server url
paths:
  /organizations:
    get:
      tags:
        - Organizations
      summary: "Retrieve the list of organizations"
      operationId: getOrganizations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrganizationDTO'
        '401':
          description: Unauthorized - Missing or invalid token
        '403':
          description: Forbidden - Access denied
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /brokers/config:
    get:
      tags:
        - Brokers
      summary: "Retrieve application information for FE"
      operationId: getBrokerConfig
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigFE'
        '401':
          description: Unauthorized - Missing or invalid token
        '403':
          description: Forbidden - Access denied
        '500':
          description: Internal Server Error
  /token:
    post:
      tags:
        - Authentication
      summary: "Generate an access token"
      operationId: postToken
      security: [ ]
      parameters:
        - name: idToken
          in: query
          required: true
          schema:
            type: string
          description: ID token from the client
      responses:
        '200':
          description: Access Token generated successfully
          content:
            application/json:
              schema:
                type: 'AccessToken'
        '400':
          description: Invalid request
        '401':
          description: Authentication failed
        '429':
          description: Too many requests
        '500':
          description: Internal Server Error
  /core-health:
    get:
      tags:
        - Monitoring
      operationId: getHealthStatus
      security: [ ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServiceStatus'
        '503':
          description: Service is unavailable
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServiceStatus'
  /taxonomy/getOrganizationTypes:
    get:
      tags:
        - Taxonomy
      summary: "Retrieve distinct organization types for FE"
      operationId: getOrganizationTypes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaxonomyOrganizationTypeDTO'
        '401':
          description: Unauthorized - Missing or invalid token
        '403':
          description: Forbidden - Access denied
        '500':
          description: Internal Server Error
  /taxonomy/getMacroArea:
    get:
      tags:
        - Taxonomy
      operationId: getMacroArea
      parameters:
        - name: organizationType
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaxonomyMacroAreaCodeDTO'
        '401':
          description: Unauthorized - Missing or invalid token
        '403':
          description: Forbidden - Access denied
        '500':
          description: Internal Server Error
  /taxonomy/getServiceType:
    get:
      tags:
        - Taxonomy
      operationId: getServiceType
      parameters:
        - name: organizationType
          in: query
          schema:
            type: string
        - name: macroAreaCode
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaxonomyServiceTypeCodeDTO'
        '401':
          description: Unauthorized - Missing or invalid token
        '403':
          description: Forbidden - Access denied
        '500':
          description: Internal Server Error
  /taxonomy/getCollectionReason:
    get:
      tags:
        - Taxonomy
      operationId: getCollectionReason
      parameters:
        - name: organizationType
          in: query
          schema:
            type: string
        - name: macroAreaCode
          in: query
          schema:
            type: string
        - name: serviceTypeCode
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaxonomyCollectionReasonDTO'
        '401':
          description: Unauthorized - Missing or invalid token
        '403':
          description: Forbidden - Access denied
        '500':
          description: Internal Server Error
  /taxonomy/getTaxonomyCode:
    get:
      tags:
        - Taxonomy
      operationId: getTaxonomyCode
      parameters:
        - name: organizationType
          in: query
          schema:
            type: string
        - name: macroAreaCode
          in: query
          schema:
            type: string
        - name: serviceTypeCode
          in: query
          schema:
            type: string
        - name: collectionReason
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaxonomyCodeDTO'
  /debt-position-types/organization/{organizationId}:
    get:
      tags:
        - DebtPositionTypes
      summary: "Retrieve a page of DebtPositionTypeWithCount based on the organization's brokerId"
      operationId: getDebtPositionTypeWithCount
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedDebtPositionTypeWithCount'
        '401':
          description: Unauthorized - Missing or invalid token
        '403':
          description: Forbidden - Access denied
        '500':
          description: Internal Server Error
      x-spring-paginated: true
  /debt-position-types/receipts:
    get:
      tags:
        - Receipts
      summary: "Retrieve a page of receipts based on filters"
      operationId: getReceipts
      parameters:
        - name: organizationId
          in: query
          required: true
          schema:
            type: integer
            format: int64
        - name: receiptOrigin
          in: query
          required: true
          schema:
            type: string
        - name: operatorExternalUserId
          in: query
          required: true
          schema:
            type: string
        - name: iuv
          in: query
          required: false
          schema:
            type: string
        - name: iur
          in: query
          required: false
          schema:
            type: string
        - name: iud
          in: query
          required: false
          schema:
            type: string
        - name: debtPositionTypeOrgId
          in: query
          required: false
          schema:
            type: integer
            format: int64
        - name: fromDate
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: toDate
          in: query
          required: false
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedReceiptView'
        '401':
          description: Unauthorized - Missing or invalid token
        '403':
          description: Forbidden - Access denied
        '500':
          description: Internal Server Error
      x-spring-paginated: true
  /debt-position-types/{id}:
    get:
      tags:
        - DebtPositionTypes
      summary: "Retrieve a specific debt position type"
      operationId: getDebtPositionType
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The unique identifier of the debt position type
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: 'DebtPositionType'
        '404':
          description: Not Found - Debt position type not found
        '401':
          description: Unauthorized - Missing or invalid token
        '403':
          description: Forbidden - Access denied
        '500':
          description: Internal Server Error
  /ingestion-flow-files/{organizationId}:
    get:
      tags:
        - IngestionFlowFiles
      operationId: getIngestionFlowFiles
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: flowFileType
          in: query
          required: true
          schema:
            type: 'FlowFileType'
        - name: creationDateFrom
          in: query
          schema:
            type: string
            format: date-time
        - name: creationDateTo
          in: query
          schema:
            type: string
            format: date-time
        - name: status
          in: query
          schema:
            type: string
            enum:
              - REQUESTED
              - PROCESSING
              - COMPLETED
              - EXPIRED
              - ERROR
        - name: fileName
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/PagedIngestionFlowFile'
        '404':
          description: Not Found
      x-spring-paginated: true
security:
  - BearerAuth: [ ]
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    TaxonomyCodeDTO:
      type: object
      properties:
        organizationType:
          type: string
        organizationTypeDescription:
          type: string
        macroAreaCode:
          type: string
        macroAreaName:
          type: string
        macroAreaDescription:
          type: string
        serviceTypeCode:
          type: string
        serviceType:
          type: string
        serviceTypeDescription:
          type: string
        collectionReason:
          type: string
        taxonomyCode:
          type: string
    TaxonomyCollectionReasonDTO:
      type: object
      properties:
        organizationType:
          type: string
        organizationTypeDescription:
          type: string
        macroAreaCode:
          type: string
        macroAreaName:
          type: string
        macroAreaDescription:
          type: string
        serviceTypeCode:
          type: string
        serviceType:
          type: string
        serviceTypeDescription:
          type: string
        collectionReason:
          type: string
    TaxonomyServiceTypeCodeDTO:
      type: object
      properties:
        organizationType:
          type: string
        organizationTypeDescription:
          type: string
        macroAreaCode:
          type: string
        macroAreaName:
          type: string
        macroAreaDescription:
          type: string
        serviceTypeCode:
          type: string
        serviceType:
          type: string
        serviceTypeDescription:
          type: string
    TaxonomyMacroAreaCodeDTO:
      type: object
      properties:
        organizationType:
          type: string
        organizationTypeDescription:
          type: string
        macroAreaCode:
          type: string
        macroAreaName:
          type: string
        macroAreaDescription:
          type: string
    TaxonomyOrganizationTypeDTO:
      type: object
      properties:
        organizationType:
          type: string
        organizationTypeDescription:
          type: string
    OrganizationDTO:
      type: object
      required:
        - organizationId
        - ipaCode
        - orgName
        - operatorRole
        - orgFiscalCode
      properties:
        organizationId:
          type: integer
          format: int64
          description: Organization ID
        ipaCode:
          type: string
          description: IPA code of the organization
        orgName:
          type: string
          description: Organization name
        operatorRole:
          type: string
          enum:
            - ROLE_ADMIN
            - ROLE_OPER
          description: Operator role
        orgLogo:
          type: string
          format: base64
          description: Base64 encoded logo of the organization
        orgFiscalCode:
          type: string
    ConfigFE:
      type: object
      required:
        - headerAssistanceUrl
        - logoFooterImg
        - footerDescText
        - footerPrivacyInfoUrl
        - footerGDPRUrl
        - footerTermsCondUrl
        - footerAccessibilityUrl
        - brokerId
        - canManageUsers
        - brokerFiscalCode
      properties:
        headerAssistanceUrl:
          type: string
          description: URL for header assistance
        logoFooterImg:
          type: string
          description: URL for footer logo image
        footerDescText:
          type: string
          description: Description text for the footer
        footerPrivacyInfoUrl:
          type: string
          description: URL for privacy information in the footer
        footerGDPRUrl:
          type: string
          description: URL for GDPR information in the footer
        footerTermsCondUrl:
          type: string
          description: URL for terms and conditions in the footer
        footerAccessibilityUrl:
          type: string
          description: URL for accessibility information in the footer
        brokerId:
          type: string
          description: Broker ID
        canManageUsers:
          type: boolean
          description: Indicates if the user can manage other users
        brokerFiscalCode:
          type: string
    ServiceStatus:
      type: object
      properties:
        serviceName:
          type: string
          description: Service Name
        statusMessage:
          type: string
          description: Service status
    ErrorDTO:
      type: object
      required:
        - title
        - description
      properties:
        title:
          type: string
          description: The title describing the error
          enum:
            - NOT_FOUND
            - BAD_REQUEST
            - GENERIC_ERROR
        description:
          type: string
          description: Description of the error
    PagedDebtPositionTypeWithCount:
      type: object
      required:
        - content
        - size
        - totalElements
        - totalPages
        - number
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/DebtPositionTypeWithCount'
        size:
          type: integer
          format: int64
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64
        number:
          type: integer
          format: int64
    DebtPositionTypeWithCount:
      type: object
      required:
        - debtPositionTypeId
        - code
        - description
        - updateDate
        - activeOrganizations
      properties:
        debtPositionTypeId:
          type: integer
          format: int64
        code:
          type: string
        description:
          type: string
        updateDate:
          type: string
          format: date-time
        activeOrganizations:
          type: integer
          format: int32
    PagedReceiptView:
      type: object
      required:
        - content
        - size
        - totalElements
        - totalPages
        - number
      properties:
        content:
          type: array
          items:
            type: 'ReceiptView'
        size:
          type: integer
          format: int64
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64
        number:
          type: integer
          format: int64
    PagedIngestionFlowFile:
      type: object
      required:
        - content
        - size
        - totalElements
        - totalPages
        - number
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/IngestionFlowFile'
        size:
          type: integer
          format: int64
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64
        number:
          type: integer
          format: int64
    IngestionFlowFile:
      required:
        - ingestionFlowFileId
        - fileName
        - creationDate
        - operator
        - status
      type: object
      properties:
        ingestionFlowFileId:
          type: integer
          format: int64
        fileName:
          type: string
        creationDate:
          type: string
          format: date-time
        operator:
          type: string
        totalRows:
          type: integer
          format: int64
        correctlyImportedRows:
          type: integer
          format: int64
        discardedRows:
          type: integer
          format: int64
        status:
          type: string
          enum:
            - UPLOADED
            - PROCESSING
            - COMPLETED
            - ERROR
