server:
  port: "\${SERVER_PORT:8080}"

spring:
    application:
      name: ${artifactId}
      version: ${version}
    jmx.enabled: true
    threads:
      virtual:
        enabled: "\${VIRTUAL_THREADS_ENABLED:true}"
monitoring:
    services:
      auth:
        serviceName: "P4PA-Auth Service"
        url: "\${AUTH_SERVER_BASE_URL:}/actuator/health/readiness"
      organization:
        serviceName: "P4PA-Organization Service"
        url: "\${ORGANIZATION_BASE_URL:}/actuator/health/readiness"
management:
    endpoints:
      jmx:
        exposure.include: "*"
      web:
        exposure:
          include: health, info, prometheus, metrics
        base-path: /actuator
    endpoint:
      health:
        probes.enabled: true
        group:
          readiness.include: "*"
          liveness.include: livenessState,diskSpace,ping
      prometheus:
        enabled: true
    metrics:
      tags:
        application: ${artifactId}
      export:
        prometheus:
          enabled: true
          step: 1m
          descriptions: true
      enable:
        jvm: true
        process: true
        system: true
        http: true
        logback: true

app:
  default-config-fe:
    headerAssistanceUrl: "\${BROKER_FE_DEFAULT_CONFIG_HEADER_ASSISTANCE_URL:DEFAULT}"
    logoFooterImg: "\${BROKER_FE_DEFAULT_CONFIG_LOGO_FOOTER_IMG:DEFAULT}"
    footerDescText: "\${BROKER_FE_DEFAULT_CONFIG_FOOTER_DESC_TEXT:PagoPA S.p.A - Società per azioni con socio unico - capitale sociale di euro 1,000,000 interamente versato - sede legale in Roma, Piazza Colonna 370, CAP 00187 - N. di iscrizione a Registro Imprese di Roma, CF e P.IVA 15376371009}"
    footerPrivacyInfoUrl: "\${BROKER_FE_DEFAULT_CONFIG_FOOTER_PRIVACY_INFO_URL:https://www.pagopa.it/it/privacy-policy}"
    footerGDPRUrl: "\${BROKER_FE_DEFAULT_CONFIG_GDPR_URL:https://www.pagopa.it/it/informativa-sul-trattamento-dei-dati-personali}"
    footerTermsCondUrl: "\${BROKER_FE_DEFAULT_CONFIG_FOOTER_TERMS_COND_URL:https://www.pagopa.it/it/termini-e-condizioni-di-utilizzo-del-sito}"
    footerAccessibilityUrl: "\${BROKER_FE_DEFAULT_CONFIG_FOOTER_ACCESSIBILITY_URL:https://form.agid.gov.it/view/c299ac76-6d08-4c34-9957-00519dde4ea9}"

rest:
  default-timeout:
    connect-millis: "\${DEFAULT_REST_CONNECT_TIMEOUT_MILLIS:120000}"
    read-millis: "\${DEFAULT_REST_READ_TIMEOUT_MILLIS:120000}"
  auth:
    base-url: "\${AUTH_SERVER_BASE_URL:}/payhub"
    tokenExchange_issuer: "\${TOKEN_EXCHANGE_ISSUER:}"
  organization:
    base-url: "\${ORGANIZATION_BASE_URL:}"
