package it.gov.pagopa.pu.bff.service.taxonomy;

import it.gov.pagopa.pu.bff.connector.organization.client.TaxonomyClient;
import it.gov.pagopa.pu.bff.dto.generated.CollectionModelTaxonomyCodeDTO;
import it.gov.pagopa.pu.bff.dto.generated.CollectionModelTaxonomyCollectionReasonDTO;
import it.gov.pagopa.pu.bff.dto.generated.CollectionModelTaxonomyMacroAreaCodeDTO;
import it.gov.pagopa.pu.bff.dto.generated.CollectionModelTaxonomyOrganizationTypeDTO;
import it.gov.pagopa.pu.bff.dto.generated.CollectionModelTaxonomyServiceTypeCodeDTO;
import it.gov.pagopa.pu.bff.mapper.CollectionModelTaxonomyCodeDTOEmbeddedToCollectionModelTaxonomyCodeDTO;
import it.gov.pagopa.pu.bff.mapper.CollectionModelTaxonomyCollectionReasonDTOEmbeddedToCollectionModelTaxonomyCollectionReasonDTO;
import it.gov.pagopa.pu.bff.mapper.CollectionModelTaxonomyMacroAreaCodeDTOEmbeddedToCollectionModelTaxonomyMacroAreaCodeDTO;
import it.gov.pagopa.pu.bff.mapper.CollectionModelTaxonomyOrganizationTypeDTOEmbeddedToCollectionModelTaxonomyOrganizationTypeDTO;
import it.gov.pagopa.pu.bff.mapper.CollectionModelTaxonomyServiceTypeCodeDTOEmbeddedToCollectionModelTaxonomyServiceTypeCodeDTO;
import org.springframework.stereotype.Service;

@Service
public class TaxonomyServiceImpl implements TaxonomyService{

  private final TaxonomyClient taxonomyClient;
  private final CollectionModelTaxonomyOrganizationTypeDTOEmbeddedToCollectionModelTaxonomyOrganizationTypeDTO collectionModelTaxonomyOrganizationTypeDTOEmbeddedToCollectionModelTaxonomyOrganizationTypeDTO;
  private final CollectionModelTaxonomyMacroAreaCodeDTOEmbeddedToCollectionModelTaxonomyMacroAreaCodeDTO collectionModelTaxonomyMacroAreaCodeDTOEmbeddedToCollectionModelTaxonomyMacroAreaCodeDTO;
  private final CollectionModelTaxonomyCollectionReasonDTOEmbeddedToCollectionModelTaxonomyCollectionReasonDTO collectionModelTaxonomyCollectionReasonDTOEmbeddedToCollectionModelTaxonomyCollectionReasonDTO;
  private final CollectionModelTaxonomyServiceTypeCodeDTOEmbeddedToCollectionModelTaxonomyServiceTypeCodeDTO collectionModelTaxonomyServiceTypeCodeDTOEmbeddedToCollectionModelTaxonomyServiceTypeCodeDTO;
  private final CollectionModelTaxonomyCodeDTOEmbeddedToCollectionModelTaxonomyCodeDTO collectionModelTaxonomyCodeDTOEmbeddedToCollectionModelTaxonomyCodeDTO;
  public TaxonomyServiceImpl(TaxonomyClient taxonomyClient,CollectionModelTaxonomyOrganizationTypeDTOEmbeddedToCollectionModelTaxonomyOrganizationTypeDTO collectionModelTaxonomyOrganizationTypeDTOEmbeddedToCollectionModelTaxonomyOrganizationTypeDTO,CollectionModelTaxonomyMacroAreaCodeDTOEmbeddedToCollectionModelTaxonomyMacroAreaCodeDTO collectionModelTaxonomyMacroAreaCodeDTOEmbeddedToCollectionModelTaxonomyMacroAreaCodeDTO,CollectionModelTaxonomyCollectionReasonDTOEmbeddedToCollectionModelTaxonomyCollectionReasonDTO collectionModelTaxonomyCollectionReasonDTOEmbeddedToCollectionModelTaxonomyCollectionReasonDTO,CollectionModelTaxonomyServiceTypeCodeDTOEmbeddedToCollectionModelTaxonomyServiceTypeCodeDTO collectionModelTaxonomyServiceTypeCodeDTOEmbeddedToCollectionModelTaxonomyServiceTypeCodeDTO,CollectionModelTaxonomyCodeDTOEmbeddedToCollectionModelTaxonomyCodeDTO collectionModelTaxonomyCodeDTOEmbeddedToCollectionModelTaxonomyCodeDTO){
    this.taxonomyClient = taxonomyClient;
    this.collectionModelTaxonomyOrganizationTypeDTOEmbeddedToCollectionModelTaxonomyOrganizationTypeDTO = collectionModelTaxonomyOrganizationTypeDTOEmbeddedToCollectionModelTaxonomyOrganizationTypeDTO;
    this.collectionModelTaxonomyMacroAreaCodeDTOEmbeddedToCollectionModelTaxonomyMacroAreaCodeDTO = collectionModelTaxonomyMacroAreaCodeDTOEmbeddedToCollectionModelTaxonomyMacroAreaCodeDTO;
    this.collectionModelTaxonomyCollectionReasonDTOEmbeddedToCollectionModelTaxonomyCollectionReasonDTO = collectionModelTaxonomyCollectionReasonDTOEmbeddedToCollectionModelTaxonomyCollectionReasonDTO;
    this.collectionModelTaxonomyServiceTypeCodeDTOEmbeddedToCollectionModelTaxonomyServiceTypeCodeDTO = collectionModelTaxonomyServiceTypeCodeDTOEmbeddedToCollectionModelTaxonomyServiceTypeCodeDTO;
    this.collectionModelTaxonomyCodeDTOEmbeddedToCollectionModelTaxonomyCodeDTO = collectionModelTaxonomyCodeDTOEmbeddedToCollectionModelTaxonomyCodeDTO;
  }
  @Override
  public CollectionModelTaxonomyCollectionReasonDTO getCollectionReason (
    String organizationType,
    String macroAreaCode, String serviceTypeCode, String accessToken){
      return collectionModelTaxonomyCollectionReasonDTOEmbeddedToCollectionModelTaxonomyCollectionReasonDTO.map(taxonomyClient.getCollectionReason(organizationType,macroAreaCode,serviceTypeCode,accessToken).getEmbedded());
  }

  @Override
  public CollectionModelTaxonomyMacroAreaCodeDTO getMacroArea (
    String organizationType,
    String accessToken) {
    return collectionModelTaxonomyMacroAreaCodeDTOEmbeddedToCollectionModelTaxonomyMacroAreaCodeDTO.map(taxonomyClient.getMacroArea(organizationType,accessToken).getEmbedded());
  }

  @Override
  public CollectionModelTaxonomyOrganizationTypeDTO getOrganizationTypes (
    String accessToken) {
    return collectionModelTaxonomyOrganizationTypeDTOEmbeddedToCollectionModelTaxonomyOrganizationTypeDTO
        .map(taxonomyClient.getOrganizationType(accessToken).getEmbedded());
  }

  @Override
  public CollectionModelTaxonomyServiceTypeCodeDTO getServiceType (
    String organizationType,
    String macroAreaCode, String accessToken) {
    return collectionModelTaxonomyServiceTypeCodeDTOEmbeddedToCollectionModelTaxonomyServiceTypeCodeDTO.map(taxonomyClient.getServiceType(organizationType,macroAreaCode,accessToken).getEmbedded());
  }

  @Override
  public CollectionModelTaxonomyCodeDTO getTaxonomyCode (
    String organizationType,
    String macroAreaCode, String serviceTypeCode, String collectionReason,
    String accessToken) {
    return collectionModelTaxonomyCodeDTOEmbeddedToCollectionModelTaxonomyCodeDTO.map(taxonomyClient.getTaxonomyCode(organizationType,macroAreaCode,serviceTypeCode,collectionReason,accessToken).getEmbedded());
  }
}
